language: cpp
dist: trusty
sudo: required

cache:
  directories:
  - deps
  - datasets


install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq python-numpy libvtk6.3 libvtk6-dev unzip libflann-dev wget mercurial git gcc cmake python-numpy freeglut3 freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev libxmu-dev libxi-dev  libboost-all-dev cvs libgoogle-glog-dev libatlas-base-dev gfortran  gtk2.0 libgtk2.0-dev l libyaml-dev

script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - gcc --version
  - make toon
  - make eigen3
  - make suitesparse
  - make g2o
  - make cvd
  - make flann
  - make gvars
  - make freeimage
  - make pangolin
  - make opengv
  - make opencv
  - make brisk
  - make ceres
  - make pcl
  - make opentuner
  - ls deps
